### ISSUE TITLE
JWTManager uses undefined function "getCredentials" of class "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken"

### ISSUE THREAD

**Issue by nourheine** [lexik/LexikJWTAuthenticationBundle#1040]
Hi guys!
I'm using symfony 6 (after i upgrade from version 5.3) , I installed the bundle lexikJWTAuthenticationBundle, now i intent to decode the created token so i refere to this documentation: 
https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/9-access-authenticated-jwt-token.html

I got this error when i use this code to decode the generated token 
Attempted to call an undefined method named "getCredentials" of class "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken"

I suppose that the decode function in Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager uses the function getCredentials that is deprecated in symfony 5.4 and removed in symfony 6.

I will appreciate any help! thanks in advance.

**Comment by fmarchalemisys** [comment]
Hi,

I just got hit by this bug.

The failure is caused by `\Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager::decode()` declared as expecting a `TokenInterface` which, as you pointed out, has no `getCredentials()` anymore.

It works when called with a `JWTUserToken`, `PreAuthenticationJWTUserToken` or `JWTPostAuthenticationToken` because they all define the `getCredentials()` method.

Unfortunately, no interface is defined to easily check the provided token is compatible with `JWTManager::decode()`.

The only solution on your side is to check the method exists on the token before trying to decode it:

```php
if (!\is_object($token) || !method_exists($token, "getCredentials")) {
    throw new \Exception("Not a jwt token");
}
$payload = $jwtManager->decode($token);
if ($payload === false) {
    throw new \Exception("Invalid jwt token");
}
```

Are you guys open to a PR adding a `JWTTokenInterface` and updating `JWTManager::decode(JWTTokenInterface $token)` (it will break custom tokens not implementing the new interface) or is the problem more structural than this (i.e. must get rid of `getCredentials()` altogether) or should the above check be included in `JWTManager::decode()` to cleanly return `false` while still accepting any `TokenInterface` ?

**Comment by chalasr** [comment]
Hi, sorry about the super late reply. but I'd need some reproducing code in order to understand the issue and eventually fix it. Please comment if you can provide that.

**Comment by fmarchalemisys** [comment]
Hi @chalasr ,

Can you tell us why this issue is closed, please?

The offending code is unchanged in [v3 branch](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/4eb6bcd9aae48c0406b97c4d847d4e05a1d6738e/Services/JWTManager.php#L96) and [v2 branch](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/675f4f3d5358c653ad28b6c60096c6127cd2a19b/Services/JWTManager.php#L108).

And, as far as I can see, [\Symfony\Component\Security\Core\Authentication\Token\TokenInterface](https://github.com/symfony/security-core/blob/7.0/Authentication/Token/TokenInterface.php) still has no `getCredentials()` method.

Running phpstan on `vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php` (v2) rightly says:

```
 ------ -------------------------------------------------------------------------------------------------------------------- 
  Line   JWTManager.php                                                                                                      
 ------ -------------------------------------------------------------------------------------------------------------------- 
  108    Call to an undefined method Symfony\Component\Security\Core\Authentication\Token\TokenInterface::getCredentials().  
 ------ -------------------------------------------------------------------------------------------------------------------- 
```

Can you provide a link to the PR fixing the issue so I can review it?

**Comment by chalasr** [comment]
I closed the issue due to the lack of reply from the OP and more precisely the lack of reproducing code.
Please provide that missing reproducer or submit a PR directly if you'd like this to be fixed. Thanks!

**Comment by fmarchalemisys** [comment]
By a reproducer code, you mean something like this?

```php
$token = new NullToken();
$this->jwtManager->decode($token);
```

Any class inheriting from `TokenInterface` will break the `decode` method. It happens on systems supporting other authentication methods apart from JWT.

As I stated, you don't even need a reproducer code. You might simply want to fix the error reported by phpstan on `vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php`, just for the sake of having a clean code :slightly_smiling_face: 

It is hard for me to propose a PR as I don't even know what would be an acceptable solution. I suggested three possibilities in [my previous message](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1040#issuecomment-1517840117).

**Comment by SebLevDev** [comment]
Same issue 
during test with phpunit i have a `$token` with T`estBrowserToken` class
in this case `$token->getCredentials() === null` and this occur an error

```
request.CRITICAL: Uncaught PHP Exception TypeError: "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider::load(): 
Argument #1 ($token) must be of type string, null given, 
called in /www/vendor/lexik/jwt-authentication-bundle/Encoder/LcobucciJWTEncoder.php on line 47" at LcobucciJWSProvider.php line 112
```

**Comment by chalasr** [comment]
PR welcome 🙏

**Comment by fmarchalemisys** [comment]
The PR is here: https://github.com/lexik/LexikJWTAuthenticationBundle/pull/1244
