### ISSUE TITLE
Issue in the authentication

### ISSUE THREAD

**Issue by anis-sabbagh** [lexik/LexikJWTAuthenticationBundle#168]
I am using LexikJWTAuthenticationBundle to authenticate in my application using REST Webservice.
I followed the instructions given in the bundle. While authentication ,the bundle generate a token but when there is no session store in th backend because when i try  `$userConnected=$this->get('security.token_storage')->getToken();` it returns null.
Here is my seurity.yml file:
```
security:
    encoders:
        AppBundle\Entity\Credentials:
            algorithm: sha1
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        our_db_provider:
            entity:
                class: AppBundle:Credentials
                property: username
                    # if you're using multiple entity managers
                    # manager_name: customer

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: our_db_provider
            form_login:
                login_path: /angularApp/app/#/Main/login
                check_path: /api/login_check
                require_previous_session: false
                use_forward: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                 authorization_header: # check token in Authorization Header
                     enabled: true
                     prefix:  Bearer
                     #name:    Authorization
                 cookie:               # check token in a cookie
                     enabled: false
                     name:    BEARER
                 query_parameter:      # check token in query string parameter
                     enabled: false
                     name:    bearer
                 throw_exceptions:        false     # When an authentication failure occurs, return a 401 response immediately
                 create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                 authentication_provider: lexik_jwt_authentication.security.authentication.provider
                 authentication_listener: lexik_jwt_authentication.security.authentication.listener
        main:
            pattern:   ^/
            http_basic: ~
            anonymous: false


    access_control:
        - { path: ^/angularApp/app/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

**Comment by chalasr** [comment]
Hi @anis-sabbagh,

> ...  but when there is no session store in th backend 

What do you mean?

After getting the token from `/api/login`, are you correctly sending the token in each request you do?
You need to pass it as Authorization header (or query parameter) in your request, same for all requests that need to be authenticated.

**Comment by anis-sabbagh** [comment]
Hi @chalasr 
But i'm getting the token from /api/login_check not from api/login. Besides, after getting this token, i try to access to a page that needs authentication by sending an Authorization header Bearer "Value of the token" the page returns a 401 response !!!

**Comment by chalasr** [comment]
@anis-sabbagh I see. 

Can you please give me the `message` part of the 401 response (should be one of "Bad credentials" or "Invalid JWT Token") ?

I need more informations about your server environment:
- On what platform your server is running? Unix/Linux, Windows?
- What kind of web server are you using? PHP built-in, Apache (if MAMP/WAMP or something like, please precise it)?

To avoid any application-related doubt, please try to perform a CURL request like shown in the documentation (or any REST client e.g. Postman). This one will be sufficient:

    curl -H "Authorization: Bearer <JWT TOKEN>" http://<YOUR_DOMAIN>/api/<RESOURCE URI>

If the CURL request doesn't work, please try to (temporarily) remove the `main` firewall of your security configuration. Then clear your cache, renew your token and make a new request with the token as header.

Thank you.

**Comment by anis-sabbagh** [comment]
Hi @chalasr . 
the 401 response indicates that the authentication failed. I am already using Postman and when i tried your Curl code it returned the same response ... . I am on windows 7 and i am using wamp server.
I have a WebService that returns the user connected ("$this->get('security.token_storage')->getToken()->getUser();") It returns an error because getToken() is null even when i removed the main firewall and cleared the cache the result is the same.

**Comment by chalasr** [comment]
@anis-sabbagh When you get the 401 response, the body looks like:

```json
{
    "code": 401,
    "message": "[MESSAGE]"
}
```

Please say me the exact message given instead of the `[MESSAGE]` placeholder.
My guess is that you are facing the Apache-related problem that alter the received JWT token.
Did you correctly configured your webserver like explained [here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users)?

**Comment by anis-sabbagh** [comment]
the body is empty 
![postman](https://cloud.githubusercontent.com/assets/17157514/15287153/e69add68-1b58-11e6-94e1-82b401eab8ed.png)
this my webserver configuration:
```
listen 8051
<VirtualHost *:8051>
DocumentRoot "C:/wamp/www/GenericMap/web"	
<Directory "C:/wamp/www/GenericMap/web">
Options Indexes FollowSymLinks MultiViews
AllowOverride none
Order allow,deny
allow from all
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
RewriteRule ^(.*)$ /app_dev.php [QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f

</IfModule>
</Directory>
</VirtualHost>
```
Thanks .

**Comment by chalasr** [comment]
The empty response was a bug that has been fixed in #142.
Please run `composer update lexik/jwt-authentication-bundle` then retry and give me the message content.

Is Apache `mod_rewrite` enabled?
[This link](http://www.blog.florian-bogey.fr/activer-la-reecriture-mod_rewrite-durl-sous-wamp.html) will help you, if it is disabled, please enable it, then retry.

Thank's

**Comment by anis-sabbagh** [comment]
I have updated the bundle and activated mod_rewrite on the server
now I am  getting this response:
![postman](https://cloud.githubusercontent.com/assets/17157514/15290368/e9336010-1b6f-11e6-9c2d-856c43344296.png)

**Comment by chalasr** [comment]
You have a problem in your web server configuration.
Sorry but your issue is too broad and not directly related to this bundle.

First, check your apache (wamp) logs in order to debug your server configuration problem.
Then, verify that the configuration of the bundle is correct (You have correctly generated the public/private keys with passphrase __and__ set the __correct__ passphrase (the one used when during  generation of the keys).

If you can't solve your issue by yourself, go on Stack Overflow (the official platform for Symfony support) and open a question [tagged with _lexikjwtauthbundle_] (http://stackoverflow.com/questions/tagged/lexikjwtauthbundle) (Take a look at the existing ones before opening yours, you may find the answer to your problem).

I close this issue for now.
