### ISSUE TITLE
Alternative to namshi/jose creation/loading library

### ISSUE THREAD

**Issue by Spomky** [lexik/LexikJWTAuthenticationBundle#181]
Hi,

I noted that you are working on a new major release of this project (#132) and I would like to take the opportunity to introduce you the [library](https://github.com/Spomky-Labs/jose) and the [bundle](https://github.com/Spomky-Labs/JoseBundle) I created.

These two projects aim to provide an implementation of the RFCs related to the Jot.
As you will see, they are already covering almost all the approved specifications and especially almost all algorithms, including encryption ones.

It will be great if you could take time to verify these projects fit on your needs.
Because the library that is currently used by this bundle is also a great library, you may create a sort of bridge to allow developers to use the library of their choice. 

The bundle is not yet marked as stable, but it is only due to the lack of documentation.
But if you have any question, I will try to answer you the best I can do.

**Comment by chalasr** [comment]
Hello @Spomky.

We have a PR in progress (code review, should be merged really soon) that goes in this way.
After this one, we'll have a DefaultEncoder that uses the Namshi/JOSE library (on which the bundle is based on). The PR firstly adds the ability to choose between the different encryption algorithms and engines available on the JWS library used.

The most important change is that these encryption settings will be passed trough configuration, and because we are already providing a simple way to create a custom encoder service, that is also directly configurable, we'll be able to create several bridges for different JWS libraries by using this configuration and passing it to our services (the encoder ones).

So, even if your library seems recent, I'll be glad to see you in a PR in order to propose a bridge of your bundle (or library directly depending on what your bundles does). 
Just subscribe to #162 to be notified when it is merged then propose changes based on (don't worry, you can be sure that it will be merged and so safely do you work based on).
You can also directly check it out and begin to work on a custom encoder as a bridge of your library, this is one of our main goals for this new major release (v2.0).

If I can give you an advice, look at the discussion in the PR I linked, there is already some good inputs about namespace idea for future bridges (`Encoder\[VENDOR]`).

I'll look more at your library in order to see if it is well tested, and maybe quickly implement it to see how it works, then be able to help you as possible to provide a bridge in this bundle. Also I be back here in case of I need some additional informations.

Hope this solves your question and helps you.
@slashfan cc

**Comment by chalasr** [comment]
After giving it a quick eye, your library sounds really interesting, well structured with nice features. 
It would be really good to have a bridge for.

**Comment by Spomky** [comment]
@chalasr I am happy to know you are interested in that work.
I will take time to propose a PR. But as I am quite busy this month, I cannot submit it by the next days.

In fact the bundle allow a deep integration onto a Symfony app by creating taylor made services. Everything in the library can become a service, including keys, algorithms...
This means you can easily inject everything in your own services: for example a keyset injected in a controller to provide public keys to clients (e.g. same as [Google API keys](https://www.googleapis.com/oauth2/v3/certs)).

I noted in the #162 that you are updating this bundle to allow other encoders to create/load the JWT.
I am just wondering why the public/private keys are still required in the bundle configuration. It should be up to the encoder to handle those parameters.

We can discuss later on these topics. Feel free to start [talking on Gitter](https://gitter.im/Spomky)

**Comment by chalasr** [comment]
@Spomky What you say is legit to me.
For now, we prefer let developers responsible of generating and managing their public/private keys when they are needed (everywhere actually, even after #162), especially for a matter of freedom, that is IMHO something important as the security of their application partially depends on.
Plus, they are no more really mandatory since https://github.com/lexik/LexikJWTAuthenticationBundle/commit/9a7c4528f4fe5d58220189bf6366b7e6ee28bd92, to allow the use of custom encoders.

In the future, why not make the actual public/private keys as an optional configuration (default) and propose a way to manage keys from the bundle side. It would be nice for people that don't care about them.

There was a similar discussion in https://github.com/lexik/LexikJWTAuthenticationBundle/pull/48#issuecomment-69625422, but rather than replacing the whole behavior by another, we should think it as an additional way to do, then let developers choose which one is the right one depending on their criteria.

Apart from that, we have the time for integrating new JW* libraries in this bundle, even if this major release (v2) is effectively a good opportunity.
For us too, it's a good opportunity to provide a second built-in JWT encoder that may be more flexible that the current one. I mean that we can imagine lots of interesting stuff, the discussion is really not closed at any point.

I started a room with you on Gitter, don't hesitate to come for discuss, I would be glad to know more about your library+bundle as I also don't have the time ATM to try it out.

**Comment by chalasr** [comment]
@Spomky As we already have an issue opened on this subject (see #132), I close this issue.
Hope we see you soon for proposing changes.
