### ISSUE TITLE
Runing 401 "Invalid credentials" with JWT in REDIRECT_HTTP_AUTHORIZATION

### ISSUE THREAD

**Issue by soltan13** [lexik/LexikJWTAuthenticationBundle#211]
Hello,
After reading and trying all fixes found, I'm a little desperate, so I finally create this issue because I could really not find a way to solve my problem.

I have a mobile app using a REST API I made on my symfony web site.
On the app I can Sign in/Register and after that access to the restricted API.

For that I use the following bundles :
FOSUser 
FOSRest
JMSSerializer
LexikJWTAuthentication

**All is working find on my local server.**

But on a 1and1 server, it's still runing 401 "Invalid credentials" when I try to access the restricted API.

The login procedure from the app is working : user and pwd are sent, the JWT is generated, sent to the app.
Than when I try to call, for exemple, /api/me, the app send back the JWT (I see it in the header:"Bearer 
xxxx") but is not any more used by Symfony !

I'm on a server running PHP in FastCGI so I put 
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1] 
```
in the .htaccess located in the web/ directory but with no success.

In the Profiler under Request I dont have any "authorization" key in **Request Header** and in **Request Server Parameters** I found my JWT under **REDIRECT_HTTP_AUTHORIZATION**.

So my question is : how I can tell symfony and all the bundles involved into the authorization process to find the JWT in  REDIRECT_HTTP_AUTHORIZATION ?

If a kind soul can help me with this problem I would be very grateful !
Many thanks in advance for your help.

**Comment by chalasr** [comment]
Hi @soltan13, even if it looks like an edge case and is surely not directly caused by this bundle (as it works fine on your local), opening this issue feels legit to me.

Not sure this can solve your problem or, if it does, not sure it is the right way to fix it (something in your server are doing redirections, moving the original header into another), but I would like you try to add the following in the firewall protected by jwt through this bundle:

```yaml
# app/config/security.yml
lexik_jwt:
    authorization_header: 
        enabled: true
        prefix:  Bearer
        name:   REDIRECT_HTTP_AUTHORIZATION
```

This will make the bundle trying to find a `REDIRECT_HTTP_AUTHORIZATION` header, then extract the jwt into in the same way as for the default value (`Authorization`).

If that works, you can avoid switching this configuration each time you switch between your 1and1 server and your dev environment by loading a different `security.yml` depending on your environment. For that, just create a specific `security_prod.yml` and `security_dev.yml`, then, rather than importing them in the `imports` section of your `config.yml`, import the corresponding file in your `config_prod.yml` and `config_dev.yml`, as it is working differently in both. 

Hope that helps. Otherwise, the problem surely come from your server stack, do not hesitate to keep me informed so we'll try to investigate deeper into its configuration.

**Comment by chalasr** [comment]
Also, you should move what you added from the `.htaccess` directly into your virtual host configuration, I'm afraid that your changes are not took in consideration due to FastCGI.

Last, do not forget to enable the mod rewrite using `RewriteEngine On` in your server config.

**Comment by soltan13** [comment]
Hi @chalasr,
Thanks for the time you spend on my  problem !

Your anwer don't solve directly the problem but put me in the right way :) 
Now I use this for my firewall :

```
# app/config/security.yml
firewalls:
    # ...
    api:
        # ...
        lexik_jwt:
            authorization_header: 
            enabled: true
            prefix:  Bearer
            name:   JW_TOKEN
```

And  changed the header name of the token sent by the app from "Authorization" to "JW_TOKEN"

As the name in the header is not "Authorization" is no more filtered by Apache and can be finded by lexik_jwt !!

I also don't even need any more this in the .htaccess 
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1] 
```
Once again thanks a lot for your help !

**Comment by chalasr** [comment]
You're welcome @soltan13
