### ISSUE TITLE
IAT should be a number, not a string

### ISSUE THREAD

**Issue by robinmonteil** [lexik/LexikJWTAuthenticationBundle#241]
Hello,

First time I participate on Github, so please excuse me if I do this wrong ;)

I just figured out that the "iat" parameter returned in the token should be a number, as the [RFC](https://tools.ietf.org/html/rfc7519#section-4.1.6) says. In v1.7.0, it returns a string.

Thank you for your work!

**Comment by chalasr** [comment]
Hello @robinmonteil,

As far as I know, when the RFC says the value must be a number, it doesn't mean it must be an _integer_, but a numeric value. So even if the primary type is indeed `string`, the value is still a number (a NumericDate as stated by the RFC). What you need for properly checking it is to cast it as an integer, e.g. `$iat = (int) $payload['iat'];`.

However, in 1.x, the claim is set by [namshi/jose](/namshi/jose), the JOSE library used by this bundle, so we can't change it to an integer. In 2.x, this value will become an integer, as for the exp claim.

I hope I fully answered you.
Thank you for contributing through opening this issue.

**Comment by chalasr** [comment]
ping @spomky, could you please confirm?

**Comment by Spomky** [comment]
Normally the `iat` cliam is a timestamp so we expect to get an integer.

The issue does not come from the bundle, but the namshi/jose library. It seems to be fixed in v7.2 but the bundle still uses `v6`.
If this dependency could be modified without BC Break then you can update it, otherwise you have to wait for the v2 of that bundle.

In any case, a token should be an obscur string for the client. Clients should not try to read it.

**Comment by chalasr** [comment]
Thank you for your complete answer.

**Comment by robinmonteil** [comment]
Thank you for your answers @chalasr and @Spomky 

I was just reporting to help, this issue is not a problem for me, so no big deal.

The "problem" is only about consistency, since the `exp` claim in the token is an integer, but hey, I think this can wait the v2.0 :)

**Comment by chalasr** [comment]
@robinmonteil Again, thank you for that.
Closing this as fixed in 2.0.
