### ISSUE TITLE
for apache users error code":401,"message":"JWT Token not found"

### ISSUE THREAD

**Issue by Lawrancecool** [lexik/LexikJWTAuthenticationBundle#270]
code":401,"message":"JWT Token not found"

<VirtualHost *:80>
        ServerName FIReports

        ServerAdmin ssiplrobert@localhost
        DocumentRoot /home/robert/Projects/ServerProjects/Projects/FIR_Reports/web/

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/fireports_error.log
        CustomLog ${APACHE_LOG_DIR}/fireports_access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
        <Directory /home/robert/Projects/ServerProjects/Projects/FIR_Reports/web/ >
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                Allow from all
                Require all granted

                RewriteEngine On
		RewriteCond %{HTTP:Authorization} ^(.*)
		RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
        </Directory>

</VirtualHost>

**Comment by chalasr** [comment]
Sorry but we can't help more than we do already on this point since we can't make your apache web server handle headers differently than it does, the authorization header extractor of this bundle can only work if the header is properly transmitted by your web server and as far as  `$_SERVER` doesn't contain an `HTTP_AUTHORIZATION` header, the problem comes from your web server which did not transmitted it. If you have an issue for enabling authorization headers on apache, please open a question on stackoverflow using the `apache` tag.

I hope you will be able to make this bundle work in your environment.
