### ISSUE TITLE
JWT and User Switch

### ISSUE THREAD

**Issue by jpillias** [lexik/LexikJWTAuthenticationBundle#271]
Hi,

It seem's that the "switch_user" wich is availaible in symfony (2.8 for me) is not compatible with LexikJWTAuthenticationBundle.

So I have create a service wich check if a X-Switch-User is present in the header.
If so, I check if current admin has ROLE_ALLOWED_TO_SWITCH. If so, he will be switched to the given user in X-Switch-User.

The problem is I don't know how to create a new JWT token and how to "store it", so the "real" loggued user has the "switch users" roles.

Thank you for your help.

**Comment by chalasr** [comment]
Hi @jpillias,

I don't know much about the `switch_user` so I'm not sure about if it is something we should provide support for (firewalls secured through JWT should be stateless), but if it is something compatible it would be great to support it. If it isn't, I will try to give you all in hand for recreating a new token. I'll try to come back with an answer for (at worse) tomorrow.

Thank you for opening this issue.

**Comment by jpillias** [comment]
Thank you for your help.

I will wait after your answer, then may try to do a PR.

**Comment by chalasr** [comment]
@jpillias after a quick look on this subject, it looks like the symfony `switch_user` feature doesn't fitimpersonating users is not compatible with this bundle:

> User impersonation is not compatible with pre authenticated firewalls. The reason is that impersonation requires the authentication state to be maintained server-side, but pre-authenticated information (SSL_CLIENT_S_DN_Email, REMOTE_USER or other) is sent in each request.

However, it looks like this is possible to achieve e.g. using a custom header like you proposed and some logic for handling the impersonation and store a new security token in the symfony token storage.

I don't yet have an exact idea of how it could be implemented but I think you should not have to create a new JWT token. Instead I think we should just submit a valid one (let's say the token is corresponding to e.g. `user1`)  and, if the `X-Switch-User` header is present in the request in addition of the JWT one (let's say it has `user2` as value), retrieve the corresponding user using the configured user provider and last, create the _security_ token using this same user (`user2`) instead of the original one (`user1`) for finally storing it in the symfony's token storage so it is authenticated.

I'm not sure about if such logic should be implemented in our `JWTTokenAuthenticator` or in a separated listener. Here is an example implementation (it is not about JWT but stateless switch user): https://github.com/lafourchette/SwitchUserStatelessBundle
Maybe you can find some inspiration into.

It would be nice to see how this could behave so I hope to see you proposing it in a PR, or at least having your feedback for how you achieved it.

**Comment by chalasr** [comment]
@jpillias Do you mind to work on this?

**Comment by jpillias** [comment]
Hi,

Yes, thank you for you link.
I'm actually working on it, and hope finish it tomorrow :)

Best regards

Julien Pillias
Responsable R&D
Mail Metrics
01.55.46.91.58
www.mail-metrics.fr - 01.43.48.44.98 Follow us:
<https://twitter.com/mailmetrics>
<https://www.linkedin.com/company/mail-metrics-by-key-performance-group->

2016-11-14 18:45 GMT+01:00 Robin Chalas <notifications@github.com>:

**Comment by teohhanhui** [comment]
Is there any reason why we can't just use SwitchUserStatelessBundle?

**Comment by chalasr** [comment]
@teohhanhui I didn't find the time to try it yet but right now I don't see any reason to don't use it

**Comment by teohhanhui** [comment]
I've just tried it out and it works seamlessly. So I don't think there's
anything we need to add in this bundle.

**Comment by chalasr** [comment]
👍  Thanks for the feedback. 
ping @jpillias

**Comment by jpillias** [comment]
Hi,

I finally done my own developpement, because I need more flexibility like
using X-Switch-header AND X-Switch-Account.

So i've done a service for it, and using quiete the same functions than
this file :
https://github.com/lafourchette/SwitchUserStatelessBundle/blob/master/Security/Firewall/SwitchUserStatelessListener.php
(handle and attemptSwitchUser).

All seems to work well, we are actually testing it.

Thank you for your help.
If you need any more informations, don't hesitate to ask me :)

Julien Pillias
Responsable R&D
Mail Metrics
01.55.46.91.58
www.mail-metrics.fr - 01.43.48.44.98 Follow us:
<https://twitter.com/mailmetrics>
<https://www.linkedin.com/company/mail-metrics-by-key-performance-group->

2016-11-16 13:05 GMT+01:00 Robin Chalas <notifications@github.com>:

**Comment by teohhanhui** [comment]
@jpillias I'm not quite sure what your additional requirements are, but it'd be great if you could contribute that to the SwitchUserStatelessBundle :smile:
