### ISSUE TITLE
How to add ROLE_API

### ISSUE THREAD

**Issue by crash21** [lexik/LexikJWTAuthenticationBundle#299]
Hello,

I am using FosRestBundle and I use:

    disable_csrf_role: ROLE_API

According this guide here: http://symfony.com/doc/current/security/api_key_authentication.html

It adds ROLE_API on the fly.

    public function loadUserByUsername($username)
    {
        return new User(
            $username,
            null,
            // the roles for the user - you may choose to determine
            // these dynamically somehow based on the user
            array('ROLE_API')
        );
    }

How can i achieve this with JWT bundle? Where is the best place to override or to which event set a listener to accomplish this?

**Comment by chalasr** [comment]
Hi @crash21,

We just added a `JWTUserProvider` to solve this kind of needs.
It creates user instances from the JWT token on each request, meaning that we don't reload the user information (e.g. roles) from the database so it would be the same until the token is renewed. 
If this behavior fits your needs, you can follow [this chapter of the documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md)  and, in [this section](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md#can-i-use-my-own-user-class), add the `ROLE_API` programmatically. 

Otherwise, you can [extend the guard jwt authenticator](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/6-extending-jwt-authenticator.md) and override the `loadUser()` method (requires version `2.1.0` of this bundle) to add the role on your user before returning it. 

However, I think it's better to give this role to your user when it is registered, and don't add any role -on the fly.
Hope this helps you.

**Comment by crash21** [comment]
Hey @chalasr,

It will be indeed better to add ROLE_API when user registers, but the problem will be then that all the time csrf will be off, but my objective is to just disable csrf when user uses API. 

Thanks anyway! I will extend jtw guard authenticator, for my needs that will be the simplest solution!

**Comment by chalasr** [comment]
Please close this issue when you're good :)

**Comment by crash21** [comment]
Hey thanks, closing.
