### ISSUE TITLE
JWT with no users

### ISSUE THREAD

**Issue by christianwico** [lexik/LexikJWTAuthenticationBundle#334]
Is it possible that I can use this bundle to authenticate a mobile app without any sort of `User` entity? My app will have no users.

**Comment by chalasr** [comment]
The symfony security system is all about a User object (see its UserInterface and TokenInterface), you can't use it to perform authentication/authorization without such object. 

The role of this bundle can be resumed in two steps:
1) Get the token (generally done by sending a _valid username-password couple_ to a login route)
2) Perform authorized requests with this token (send the token via e.g. header to any route you made protected by this bundle).

For 2, this bundle provides [a db-less user provider](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md): authentication is made from the token content rather than loading an user based on the token content, the token is always trust. Using this provider is optional. The default behavior is to load an user from the datastore each time a token is submitted, and forbid access in case no user can be found.

But 1 requires an user, first to forge the jwt, then to create the TokenInterface object leading to authorization.

So the question is: on what criteria should your app deliver tokens?
Should any request to your login endpoint return a token without performing any verification on those requests? I can't imagine a scenario where you want anyone able to be authenticated to your mobile app.
Or are your users stored elsewhere (not on your server) and you want to perform this validation client-side only? That would be difficult to end up with a secure scenario.

**Comment by kopaygorodsky** [comment]
@chalasr @christianwico  I think he wants to track user actions without required sign up. 
What if creating a user based only on UUID(unique phone id) until the user signs up with username and password.  Is it possible? I think some new Tokens and provides can help, right?

**Comment by fd6130** [comment]
> The symfony security system is all about a User object (see its UserInterface and TokenInterface), you can't use it to perform authentication/authorization without such object.

+1

>  I think he wants to track user actions without required sign up.

Sounds like out of topic from this bundle?

**Comment by sukhoy94** [comment]
@christianwico, @chalasr, I had similar issues, and I figured it out in that way:

1. create firewall for routes which you want to protect with jwt for requests from your mobile app (without user, so it's like server-server communication):

```
// security.yaml
secure_firewall_mobileapp: 
            pattern: ^/mobile_api
            provider: jwt
            jwt:
                authenticator: app.custom_authenticator_mobile
```

2. Then in your custom authenticator just check if your app send jwt (notice that you should generate for your app jwt programmatically using same private key as for your server application)

```
<?php

declare(strict_types=1);

namespace App\Security;

use Lexik\Bundle\JWTAuthenticationBundle\Exception\ExpiredTokenException;
use Lexik\Bundle\JWTAuthenticationBundle\Exception\InvalidTokenException;
use Lexik\Bundle\JWTAuthenticationBundle\Exception\JWTDecodeFailureException;
use Lexik\Bundle\JWTAuthenticationBundle\Exception\JWTFailureException;
use Lexik\Bundle\JWTAuthenticationBundle\Exception\MissingTokenException;
use Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator;
use Symfony\Component\HttpFoundation\Request;


// notice that you should extends JWTAuthenticator
class MobileApiSecurityAuthenticator extends JWTAuthenticator
{
    public function supports(Request $request): ?bool
    {
        $token = $this->getTokenExtractor()->extract($request);

        if (!$token) {
            return null;
        }

        try {
            $payload = $this->getJwtManager()->parse($token);
        } catch (JWTFailureException $exception) {
            return null;
        }

        if (
            array_key_exists('iss', $payload) &&
            'mobile_app' === $payload['iss'] && // send some meta data from your app to check it
            array_key_exists('sub', $payload) &&
            'access_secure_mobile_route' === $payload['sub']
        ) { // if everything is all right, just give access to endpoint
            return false;
        }

        return null;
    }

    /**
     *
     * @return void
     */
    public function doAuthenticate(Request $request)
    {
        $token = $this->getTokenExtractor()->extract($request);

        if (!$token) {
            throw new MissingTokenException();
        }

        try {
            if (!$this->getJwtManager()->parse($token)) {
                throw new InvalidTokenException();
            }
        } catch (JWTDecodeFailureException $e) {
            if (JWTDecodeFailureException::EXPIRED_TOKEN === $e->getReason()) {
                throw new ExpiredTokenException();
            }

            throw new InvalidTokenException('Invalid JWT Token', 0, $e);
        }

        throw new InvalidTokenException();
    }
}
```

Basic idea here, is that your routes should have public_access, but you must manually check JWT for them, and if it doesn't suit your needs, you throw exceptions from JWTAuthenticator. If everything is okay, then you just return false from supports method, which means that firewall will be skipped. Here is documentation https://symfony.com/doc/current/security/custom_authenticator.html
