### ISSUE TITLE
How to allow CORS requests

### ISSUE THREAD

**Issue by DylanGD** [lexik/LexikJWTAuthenticationBundle#341]
Hi!

I use this Bundle + **NelmioCorsBundle**, the documentation says about CORS requests : 

> The important thing to note here is that both the login and api firewalls paths (in our example /api/login_check and /api) must be configured to allow CORS requests.

I have not find any doc or conf about to help us to configure it correctly ? 

Thanks

**Comment by chalasr** [comment]
Hi @DylanGD.

The documentation you pasted say ` both the login and api firewalls paths must be configured to allow CORS requests.`, which is the case in the attached code example because `^/api/` covers  the login path `/api/login` as well as all other routes.
If your routing is different than this one (e.g. the login path is `/foo/login` and the protected api is `/api`), just add a second entry with the corresponding pattern as key.
If you don't get what I mean, please look at the NelmioCorsBundle documentation or open an issue in the bundle itself, we can't help more than we do already as this bundle is just different, we only recommend it for solving this specific need but we'll not rewrite its doc.

Thanks for your understanding
