### ISSUE TITLE
[ASK] Use Load Balancer Client

### ISSUE THREAD

**Issue by ad3n** [lexik/LexikJWTAuthenticationBundle#348]
When i use load balancer in my frontend app, the auth is not working properly and always return 401

```
{"code":401,"message":"An authentication exception occurred."}
```

I don't known, it is from symfony side or bundle side, may you can explain how that issue is producing and how to solve

**Comment by chalasr** [comment]
Did you looked at [_How to Configure Symfony to Work behind a Load Balancer or a Reverse Proxy_](http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html)?
If it doesn't help, I suggest you to first disable the bundle and try another authentication listener (form_login, http_basic, ...) to be sure that the problem comes from the bundle doubt that your problem comes from the bundle. Anyway, better ask this on stackoverflow. 
Thanks for your understanding.

**Comment by ad3n** [comment]
@chalasr : Thanks for your answer but this is not Symfony App but Frontend App. I have multiple client with behind Load Balancer, the session is shared by redis and it work properly.

My problem is, when i use token (getting from the Symfony App use it bundle), The Symfony is always returning 401 like my first post.

That is the problem... I have no problem with Symfony Behind Proxy

**Comment by tamert** [comment]
@ad3n are you fixed ? and how ?
