### ISSUE TITLE
Authentication by Webservice

### ISSUE THREAD

**Issue by damienfern** [lexik/LexikJWTAuthenticationBundle#425]
Hi,

I'm developing a API REST with Symfony 4. To do it, I installed the recipe API Platform and everything went fine. Now I would like authenticate every request by a token. But the authentication is done by another webservice :  I send the credentials by SOAP and it responses by true or false depending on the success or the failure. My class and my functions to do so are already done and the only thing I can't figure it out is how to implement it in LexikJWTAuthenticationBundle. I succeed to get a token with the provider "in-memory".

Hope you guys understand me and I thank you in advance for your time :)

**Comment by chalasr** [comment]
Hey,

In order to answer you as best as possible, I need to know if you want to call your SOAP webservice each time a token is submitted (e.g. calling it once for getting the token, and once per token-authenticated request for validating its authorization scope, roles, lock...)?

In any case, you'll need a custom user provider (alternative to in_memory) for loading your user when the form login is submitted. The rest will depend on my previous question

**Comment by damienfern** [comment]
I would like to call the SOAP service when the user log in (to check if user credentials are correct). Then I only check if the token given in each request is still the same.

Thank you for your help :)

**Comment by chalasr** [comment]
I suggest you to not store tokens and always call your soap client instead, as your user might have changed between requests (e.g. permissions).
As explained, you need a custom user provider (which would call the SOAP service and store the result in an array indexed by token if you really want it). 
Here are the documentation that explains how to do so: https://symfony.com/doc/current/security/custom_authentication_provider.html.
Closing here, please checkout [Symfony support platforms](https://symfony.com/support) if you need more help.
Thanks
