### ISSUE TITLE
last_login updated each request

### ISSUE THREAD

**Issue by Preovaleo** [lexik/LexikJWTAuthenticationBundle#481]
Hello,

I just made the upgrade to disable this deprecation messages : 
```
The "lexik_jwt_authentication.security.authentication.entry_point.main" service is deprecated since LexikJWTAuthenticationBundle version 2.0 and will be removed in 3.0
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Http\EntryPoint\JWTEntryPoint" class is deprecated since version 2.0 and will be removed in 3.0. Use "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" instead.
The "security.authentication.listener.jwt.main" service is deprecated since LexikJWTAuthenticationBundle version 2.0 and will be removed in 3.0
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Firewall\JWTListener" class is deprecated since version 2.0 and will be removed in 3.0.
The "security.authentication.provider.jwt.main" service is deprecated since LexikJWTAuthenticationBundle version 2.0 and will be removed in 3.0
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Provider\JWTProvider" class is deprecated since version 2.0 and will be removed in 3.0. See "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" instead.
```

I don't know if this is a bug or a feature but, with the "new" guard configuration, each time i do a request to my symfony back-end, Symfony update the last_login field in the database. In my case, that could be problematic because it add a call to the database at each request.

im going from this config in my security.yml
```
        main:
            lexik_jwt: ~
```
To:
```
        main:
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```
My question : is it possible to disable this "alter table" or is this a symfony kernel feature

regards,

**Comment by chalasr** [comment]
I guess you have your own symfony's authentication_success event listener whose job is to update that `last_login` field, right? In that case, the fact it is triggered seems expected to me since symfony authentication does happen. What you could do is to change the event you're listening on for updating this field, e.g. switching to our [`AUTHENTICATION_SUCCESS`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsauthentication_success---adding-public-data-to-the-jwt-response) event which is fired each time a token is *delivered*. 
I'm closing as this does not look like a bug, this bundle only reads from your user object, no alteration is performed.
