### ISSUE TITLE
What's the result of going to /api/login?

### ISSUE THREAD

**Issue by riyunoa** [lexik/LexikJWTAuthenticationBundle#54]
Hi, 
Thanks for creating this bundle. I'm using it with FOSUser, /api/login_check works as expected and returns the JWT when the correct username and password are POSTed. 

But what controller action is /api/login (set in the firewalls section of security.yml) supposed to map to? For me it's going to FOSUser's login form which isn't correct for an API, but this is the default FOSUser behaviour, I haven't defined any custom routes for /api/login, do I need to?

Here's my [security.yml] (https://github.com/riyunoa/gilliblog/blob/master/app/config/security.yml).

Thanks in advance :)

**Comment by slashfan** [comment]
Hi,

Well the sample security config was just provided as a quick example but you're right it might be a little confusing :) 

In the context of an API you just need the login_check route, which will receive the user credentials just like submitting a form would. I guess you're safe to limit this firewall to `^/login_check` instead of `^/login`.

Let us know if it helps !
