### ISSUE TITLE
Security vulnerability in namshi/jose

### ISSUE THREAD

**Issue by dopgm** [lexik/LexikJWTAuthenticationBundle#57]
Hi,

This bundle uses "namshi/jose" version ~1.2 (1.2.2 as of April 4), however there's a note on namshi's page:
"Unsecure JWSes are disabled by default since version 2.1.2. You should not use previous versions other than 1.0.2, 1.1.2, 2.0.3 as they have a security vulnerability."
Also, not sure if related or not, but tokens provided by the LexikJWTAuthenticationBundle do not pass verification on jwt.io - says "Invalid Signature".

Thank you!!
D.O.

**Comment by slashfan** [comment]
Hi,

Thanks for the heads up, I thought all minor versions were fixed. I just released a [new tag](https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v1.0.7) which resolves the problem.

About the jwt.io problem you describe, as you can see they decode the token right, but fail to validate signature because they don't use the RSAxxx algorythm which requires a couple of ssh keys, but HMACxxx wich works a secret key. 

There is a PR pending to add such encoder, I'll try to make it available for 1.1.0 version.

Hope it helped :)

**Comment by dopgm** [comment]
Thanks so much!!

Dennis




________________________________
