### ISSUE TITLE
clock_skew parameter wont work in my case.

### ISSUE THREAD

**Issue by mu4ddi3** [lexik/LexikJWTAuthenticationBundle#573]
PROPOSED SOLUTION ADDED:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Solution to below problem can be like this:

`if (!$jwt->validate(new ValidationData(time() + $this->clockSkew))) {`

instead of 

`if (!$jwt->validate(new ValidationData())) {`

in **LcobucciJWSProvider.php** (inside function verify)

Thanks to this clockSkew parameter is back in game and everything works like a charm.
Pull request created.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

ORIGINAL PROBLEM:
I use newest 2.5.4 and even dev-master version. Problem exist in both.

I have "**clock_skew**" parameter configured in lexik_jwt_authentication.yaml with value 30 (my servers got around 5sec diff)

Unfortunately when i try to verify newly created (in other server) token i got into this issue:

In **LcobucciJWTEncoder.php**, in method **decode**, there is a  **load**  method running from jwsProvider. (which is **load**  method of **LcobucciJWSProvider.php**.)

This method should return
`return new LoadedJWS($payload, $this->verify($jws), null !== $this->ttl, $jws->getHeaders(), $this->clockSkew);`

As you can see it has "**$this->verify($jws)**" in constructor so it is called first and this ugly one return **FALSE** dealing damage. 
Why? Because when you go into  it you will see, that it tries to run "**validate**" method on $jwt ($jwt is **Lcobucci\JWT\Token**). 
This **validate**  method runs foreach on every claims it found (iat, nbf, etc...) and as value to check with, it uses **Lcobucci\JWT\ValidationData** object which is created and injected into this validate method. 
This object sets it's values as time() if created without params (and current, it is created without params)
Because of this, checks fails as there is no place where clockSkew parameter is taken into game at this moment.

**Comment by Pontax** [comment]
Why has the issue been closed ?

**Comment by mu4ddi3** [comment]
it was fixed in 2.6.0 as far i remembered.

**Comment by chalasr** [comment]
Yes https://github.com/lexik/LexikJWTAuthenticationBundle/pull/574

**Comment by mrfijas** [comment]
@chalasr should it really be that way?
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/9e0304726d13e67cdb9f051b9680d1ae77d0b1e8/Services/JWSProvider/LcobucciJWSProvider.php#L155
second argument of `ValidationData` is `leeway`;
now it creates `validationData` object with same timestamps for `iat`, `nfb` and `exp` (because default leeway = 0):
```php
$this->items['iat'] = $currentTime + $this->leeway;
$this->items['nbf'] = $currentTime + $this->leeway;
$this->items['exp'] = $currentTime - $this->leeway;
```
> source https://github.com/lcobucci/jwt/blob/a11ec5f4b4d75d1fcd04e133dede4c317aac9e18/src/ValidationData.php#L101-L103

which brakes `exp` claim - it should be less than `iat`.

shouldn't it be more like:
```php
if (!$jwt->validate(new ValidationData(time(), $this->clockSkew))) {
```
?

I was surprised that my JWT related tests fail when using `lexik_jwt_authentication.clock_skew = 10` and trying to validate token with payload: `['exp' => Carbon::parse('+5 seconds')->getTimestamp()]`
