### ISSUE TITLE
Upgarde to 2.6 (deprecation)

### ISSUE THREAD

**Issue by medev87** [lexik/LexikJWTAuthenticationBundle#599]
I got this deprecation when i upgarde to 2.6

The "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\DefaultJWSProvider" class is deprecated since version 2.5 and will be removed in 3.0. Use "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider" or create your own "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\JWSProviderInterface" implementation instead.

Any help ?

**Comment by adrienrn** [comment]
Hello,

Your warning seems to be triggered because of a config `lexik_jwt_authentication.encoder.service`. Did you override this configuration in your app configuration ? By default, it should use `lexik_jwt_authentication.encoder.lcobucci` that is the current preferred way and should not trigger any warning.

See here:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#full-default-configuration


PS: I'm only passing by and looking at my own issue.

**Comment by Elsilent** [comment]
Also got same deprecation on 2.6.3 version.
Configuration encoder service resolved to: _lexik_jwt_authentication.encoder.lcobucci_

Encoders in service argument  are also using this alias.

Any ideas why this could happen ?

Thanks !
