### ISSUE TITLE
User provider without implementing UserInterface

### ISSUE THREAD

**Issue by jolleychris** [lexik/LexikJWTAuthenticationBundle#708]
Using symfony 3.4 (updating soon!!)
Using Lexik JWT 2.4.0

I have a bespoke arrangement of users, credentials etc where the credential and the user fields are stored separately to each other in different entities. I also do not have a field 'email', and there are other aspects of UserInterface that I do not want to implement. 

I just wish to return an entity from my provider and use that to represent the user, without that entity implementing UserInterface.

I tried creating a custom authenticator and copied the contents of the Lexik default one, supplied with the bundle. I tried changing the getUser() method but I still get the exception that my entity does not implement UserInterface. getUser must return an instance of a UserInterface.

It all works fine of course if I change my Entity so that it does implement UserInterface. 

Please help, I'm so close to a solution I've had in mind for years, other than this unexpected issue.

**Comment by EresDev** [comment]
I have been able to successfully implement this idea in my recent project. I don't like UserInterface getting into my domain objects.  I am going to show you how to do it. You will have to write a few classes to decouple from Symfony Security and get the expected result. 

1.  You will have a User entity or any entities or number of enttites, really doesn't matter. [Here ](https://github.com/EresDev/Handwerker/blob/master/src/Domain/Entity/User.php)I have a user entity that does not implement UserInterface. 

2. You need an implementation of UserInterface to fulfil a contract with Symfony Security. I call it UserAdapter. The only purpose of this class is to make Symfony Security happy, do not use it anywhere else. It is only for Symfony Security. You use your normal User entity in other places in your app. [Here ](https://github.com/EresDev/Handwerker/blob/master/src/Infrastructure/Security/Symfony/UserAdapter.php)is the one I wrote. 

3. You need a custom UserLoader that loads a normal User entity but gives a UserInterface implementation to Symfony Security. [Here ](https://github.com/EresDev/Handwerker/blob/master/src/Infrastructure/Security/Symfony/UserLoader.php)is mine. 

4. You need a SecurityAdapter to get User object in the controller from Security instead of UserInterface. [Here ](https://github.com/EresDev/Handwerker/blob/master/src/Infrastructure/Security/Symfony/SecurityAdapter.php)is mine. 

5. Finally, your security config. What is different here from normal is that you need the same encoders for User and UserAdapter. You need to specify your custom UserLoader. Rest is normal security config.

I will be writing a detailed blog post about it soon but I think it is enough for your now to get started. 
Good luck.

**Comment by fd6130** [comment]
You still have to use UserProvider if you want to work with Symfony Security.
