### ISSUE TITLE
Is it compatible with Symfony new Authenticator-based Security?

### ISSUE THREAD

**Issue by fd6130** [lexik/LexikJWTAuthenticationBundle#810]
Hi, just asking if this bundle compatible with Symfony 5.2 new authenticator?

After i enable the new feature and remove the `annonymous` key from `security.yaml`, when i try to login it will use `JsonLoginAuthenticator` instead of the authenticator from this bundle.

**Comment by andrewalf** [comment]
I guess bundle needs some fixes. I'm trying to enable it right now and faced with error:
`Argument 1 passed to Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator() must implement interface Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface, instance of Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator given`

**Comment by chalasr** [comment]
The new authenticator system is compatible with guard. That means you need to configure the jwt authenticator the same way as before (i.e. add it to the `security.[firewall].guard.authenticators` list).

However, this bundle should provide an implementation of the new `AuthenticatorInterface` in order to remove the deprecate and remove the guard integration when it's time to.
A pull request doing so would be much appreciated.
