### ISSUE TITLE
Cookie split renewal

### ISSUE THREAD

**Issue by bpolaszek** [lexik/LexikJWTAuthenticationBundle#956]
Hello there,

I just discovered the [split cookie approach](https://medium.com/lightrail/getting-token-authentication-right-in-a-stateless-single-page-application-57d0c6474e3) which I found very interesting, and I wanted to give it a try with this bundle.

I just have one question: the author says:
>  Unless the user takes an action (thereby resulting in an API call and a new header.payload cookie with a new expiry), their header.payload cookie will expire and they will be no longer authenticated.

From what I observed, the access token here is only issued when the user exchanges their credentials (i.e. `POST /api/login_check`), and not upon every API request. Is that intended, or is there something I missed to enable that?

Thanks!
Ben

PS: Would you consider opening the "Discussions" panel on that repository so that my questions don't pollute the actual "Issues"? 😅

**Comment by JeremyPasco** [comment]
Hello, from my understanding of it: the signature cookie should not get expiration, so it becomes a "session cookie" and will be destroyed when the browser closes.
So that's the other cookie (header+payload) with a 30min lifetime that will be responsible of logging the user out in case of inactivity.
In case of activity, the cookie expiration should be increased. 2 ways to do it:
- the backend send the same cookie again with a new expiration. I fell like it was the idea behind the article you mentionned, a solution have been proposed here: #809 
- the frontend could also listen for successfull calls to the backend and increase the cookie lifetime (since this cookie it is not a httponly one)

The frontend could also trigger a prompt if the cookie lifetime expired.

**Comment by bpolaszek** [comment]
Yes, the signature cookie should be a "session" cookie, httpOnly. But I assume that when the other cookie gets renewed, the signature cookie has to be renewed as well, otherwise signature won't match on the next API call (because `iat` / `exp` would change the payload).

When Peter Locke says
> Unless the user takes an action (thereby resulting in an API call and a new header.payload cookie with a new expiry), their header.payload cookie will expire and they will be no longer authenticated.

I assumed that every subsequent API request (not especially login-related) would result in the renewal of both cookies, so that's what I expected when trying the split-cookie feature from this bundle.

OTOH issuing a new token upon each request is a costly operation that would burn the server down, wouldn't it? 

How about exposing a dedicated endpoint instead (which could still be the same route, i.e. `/api/login_check`), that the front-end would periodically hit in the background, with an empty payload (just cookies)? That endpoint would read the existing JWT as input and issue a new one through the 2 cookies. Thoughts?

**Comment by JeremyPasco** [comment]
> I assume that when the other cookie gets renewed, the signature cookie has to be renewed as well, otherwise signature won't match on the next API call (because iat / exp would change the payload).

I'm not sure about this. The token ttl was put to 24h in the article, so the iat / exp would be valid during the whole user activity. By renewing the cookie with the frontend, you only increase the hp cookie lifetime, without modifying the token ttl, iat or exp. So the signature won't change. If the backend renews it, it could just send the exact same cookie back, except for its lifetime that would be increased. Therefore, no costly operation would be triggered.

But... with the backend cookie renewal approach, I can't see how we can benefit from the cache layer anymore: any response becomes user specific because it includes the setCookie http header.

**Comment by bpolaszek** [comment]
Oh, that's awesome! 

Having the token expiring way later (24h) wasn't something I had in mind - I didn't pay enough attention about that information in the article.

Regarding cache - I'm not 100% familiar with this (especially for private resources). I assume cache proxies systematically serve MISS responses as soon as a `Set-Cookie` header is encountered (at least I hope so 😅).

How about exposing a dedicated endpoint to renew the cookie's expiration, so that it's not sent upon every request (hence cache could still be leveraged, I assume), that would allow the front-end to anticipate by periodically calling it in the background?

**Comment by JeremyPasco** [comment]
Indeed, it will serve MISS but it's easy to config a Varnish to avoid this behaviour by ignoring these 2 cookies. So the cache layer is still an option. But if the cookie is also returned for every request, the cache response has to be completed with a Set-Cookie (still possible but harder and a bit slower in my opinion).

Concerning the renewal endpoint, its job would only be to renew the cookie expiration right? If so I would rather keep that job in the frontend. It avoids the need to make a request.
My current approach is to intercept all api calls in JS and, if the user still got both cookies AND the response status is a 2XX, then I can increase the cookie lifetime.

**Comment by bpolaszek** [comment]
Didn't think about that - sounds very good 🙂 

Thanks a lot for your explanations! 🍻
